name = "armrest-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "armrest-db"
database_id = "cf82a0eb-70b5-4605-bbb9-ba0bf07f94cc"

[vars]
NODE_ENV = "production"

[triggers]
crons = ["0 8 * * *"]
